### ISSUE TITLE
span.selectortest-used-selector not entity encoded

### ISSUE THREAD

**Issue by ryancramerdesign** [niklaka/ProcessSelectorTest#1]
The output in span.selectortest-used-selector is not entity encoded and seems to be open to XSS. Not really a security concern given that this is an admin-only tool, but the result is that selectors using greater than/less than signs aren't echoed back correctly. For instance, I was using this selector: 

```
date<today
```

and got this output:

```
27 pages found with selector"date
```

I recommend running the contents of that selectortest-used-selector through wire('sanitizer')->entities().

**Comment by niklaka** [comment]
Thanks Ryan! I'll go and fix this right away.
